# Generated by Django 6.0.7 on 2026-07-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('raw_length', models.IntegerField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('fr', 'French'), ('pl', 'Polish'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Chinese')], max_length=2)),
                ('reading', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_seen_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='knowledge.wikidocument')),
            ],
            options={
                'unique_together': {('text', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TranslationEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MARKDOWN', 'Declared in Markdown'), ('AI', 'AI-generated')], max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='knowledge.term')),
                ('to_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='knowledge.term')),
            ],
            options={
                'unique_together': {('from_term', 'to_term')},
            },
        ),
        migrations.CreateModel(
            name='SymbolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('phrase', models.CharField(max_length=512)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_mappings', to='knowledge.wikidocument')),
            ],
            options={
                'unique_together': {('document', 'symbol')},
            },
        ),
    ]
